version: '3.1'
services:
    db:
        image: postgres:15
        env_file:
        - .env
        restart: always
        volumes:
        - ./postgresql:/var/lib/postgresql/data
    odoo:
      container_name: odoo
      image: odoo:16
      platform: linux/amd64
      volumes:
          - ./addons-extra:/mnt/extra-addons
          - ./config:/etc/odoo
          - ./odoo-web-data:/var/lib/odoo
      ports:
          - "3000:3000"
    nginx:
      container_name: nginx
      image: nginx:latest
      restart: unless-stopped
      ports:
          - 80:80
      volumes:
          - ./nginx/conf:/etc/nginx/conf.d
volumes:
    odoo-web-data:
