version: '2'
services:
  db:
    image: postgres:15
    user: root
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: always
    volumes:
      - ./postgresql:/var/lib/postgresql/data

  odoo16:
    image: odoo:16
    user: root
    environment:
      - HOST=db
      - USER=${POSTGRES_USER}
      - PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - db
    ports:
      - "3000:3000"  
    volumes:
      - ./customs_addons:/mnt/extra-addons
      - ./etc:/etc/odoo
    restart: always

  nginx:
    image: nginx:1.23-alpine  
    depends_on:
      - odoo16
    ports:
      - "80:80"           
    restart: always
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d  
      - ./nginx/log:/var/log/nginx      
